services:
  web:
    build: .
    container_name: webserver
    depends_on:
      - mysql
  mysql: 
    container_name: sqlserver
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Pass"
      MYSQL_USER: mobina
      MYSQL_PASSWORD: Pass2
    volumes:
      - ./initialdb:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
  
